variables:
  CIMPL_SERVICE: storage-cimpl                          
  CIMPL_BUILD_PATH: "storage-core-plus/cloudbuild/Dockerfile"
  CIMPL_HELM_PACKAGE_NAME: core-plus-storage-deploy             
  CIMPL_HELM_TIMEOUT: "--timeout 15m"
  CIMPL_TEST_PROJECT: "storage-test-core,storage-test-baremetal"
  CIMPL_TEST_SUBDIR: "testing/storage-test-baremetal"
  DISABLE_INTEGRATION_TEST: true

cimpl-deploy:
  variables:
    CIMPL_SERVICE: "storage"

cimpl-acceptance-test:
  variables:
    OPA_INTEGRATION_ENABLED: "false"
    EXPOSE_FEATUREFLAG_ENABLED: "true"

#dev2 jobs

cimpl-dev2-deploy:
  variables:
    CIMPL_SERVICE: "storage"

cimpl-dev2-acceptance-test:
  variables:
    OPA_INTEGRATION_ENABLED: "false"
    EXPOSE_FEATUREFLAG_ENABLED: "true"
    
#osdu-main jobs

cimpl-dev-deploy:
  variables:
    CIMPL_SERVICE: "storage"

cimpl-dev-acceptance-test:
  variables:
    OPA_INTEGRATION_ENABLED: "false"
    EXPOSE_FEATUREFLAG_ENABLED: "true"

cimpl-dev-backup-deploy:
  variables:
    CIMPL_SERVICE: "storage"

cimpl-dev-backup-acceptance-test:
  variables:
    OPA_INTEGRATION_ENABLED: "false"
    EXPOSE_FEATUREFLAG_ENABLED: "true"
